# Generated by Django 5.0.3 on 2024-04-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='SLUG')),
                ('price', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=100)),
                ('inventory', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'db_table': 'kiosk_menus',
                'ordering': ('name',),
            },
        ),
    ]
