# Generated by Django 5.0.3 on 2024-04-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_remove_menu_img_menu_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='explain',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='translate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
